<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2020-01-16T22:01:28 CET" name="Default suite" finished-at="2020-01-16T22:02:38 CET" duration-ms="70195">
    <groups>
    </groups>
    <test started-at="2020-01-16T22:01:28 CET" name="Default test" finished-at="2020-01-16T22:02:38 CET" duration-ms="70195">
      <class name="humanityTests.LoginTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:humanityTests.LoginTest@50caa560]" started-at="2020-01-16T22:01:28 CET" name="setup" finished-at="2020-01-16T22:01:36 CET" duration-ms="8605" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="basicLogin()[pri:0, instance:humanityTests.LoginTest@50caa560]" started-at="2020-01-16T22:01:36 CET" name="basicLogin" finished-at="2020-01-16T22:02:05 CET" duration-ms="28719" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- basicLogin -->
        <test-method signature="dashboardTest()[pri:1, instance:humanityTests.LoginTest@50caa560]" started-at="2020-01-16T22:02:05 CET" name="dashboardTest" finished-at="2020-01-16T22:02:06 CET" duration-ms="724" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dashboardTest -->
        <test-method signature="addEmployeeTest()[pri:20, instance:humanityTests.LoginTest@50caa560]" started-at="2020-01-16T22:02:06 CET" name="addEmployeeTest" finished-at="2020-01-16T22:02:35 CET" duration-ms="29512" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[did not expect to find [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: did not expect to find [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at humanityTests.LoginTest.addEmployeeTest(LoginTest.java:74)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addEmployeeTest -->
        <test-method is-config="true" signature="quit()[pri:0, instance:humanityTests.LoginTest@50caa560]" started-at="2020-01-16T22:02:35 CET" name="quit" finished-at="2020-01-16T22:02:38 CET" duration-ms="2490" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
      </class> <!-- humanityTests.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
